import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Cloud } from "lucide-react";

export function RecommendationsPanel() {
  return (
    <Card className="border-border/50">
      <CardHeader className="flex-row items-start justify-between space-y-0 gap-4">
        <div className="flex items-start gap-2">
          <div className="h-8 w-8 rounded-md bg-primary/10 flex items-center justify-center">
            <Sparkles className="h-4 w-4 text-primary" />
          </div>
          <div>
            <CardTitle className="text-base">AI Recommendations</CardTitle>
            <CardDescription className="text-xs">
              Daily decisions ranked by impact — what to do next.
            </CardDescription>
          </div>
        </div>
        <Badge variant="outline" className="text-[10px] uppercase gap-1 bg-muted/50">
          <Cloud className="h-3 w-3" />
          Backend pending
        </Badge>
      </CardHeader>
      <CardContent>
        <div className="rounded-lg border border-dashed border-border/60 bg-muted/20 p-6 text-center space-y-3">
          <div className="mx-auto h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
            <Sparkles className="h-5 w-5 text-primary" />
          </div>
          <div className="space-y-1">
            <p className="text-sm font-medium">AI engine not deployed yet</p>
            <p className="text-xs text-muted-foreground max-w-sm mx-auto leading-relaxed">
              Recommendations are generated by an Edge Function that hasn't been deployed
              to your Supabase project yet. The UI is ready — once the function is live,
              ranked decisions will appear here automatically.
            </p>
          </div>
          <div className="flex items-center justify-center gap-2 pt-1 text-[11px] text-muted-foreground">
            <span className="font-mono px-1.5 py-0.5 rounded bg-muted border border-border/60">
              generate-recommendations
            </span>
            <span>· deploy via Supabase CLI to activate</span>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
